### ISSUE TITLE
It is hard to reason why all these inputs are `required`.

### ISSUE THREAD

**Issue by asturza2** [mygainwell/acuity-actions#20]
It is hard to reason why all these inputs are `required`.

`infrastructure-setup` has 4 required inputs. 

```
        uses: mygainwell/acuity-actions/infrastructure-setup@terraform-compliance
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
```

`infrastructure-plan` has only have 1 input. The `infrastructure-path` to changes.

```
      - name: "Infrastructure Plan"
        uses: mygainwell/acuity-actions/infrastructure-plan@terraform-compliance
        with:
          infrastructure-path: stacks/github/actions
```

_Originally posted by @asturza2 in https://github.com/mygainwell/acuity-actions/pull/9#discussion_r765134982_
